spring:
  cloud:
    gateway:
      routes:
#        - id: after_route
#          uri: https://www.baidu.com/
#          predicates:
#            - After=2020-06-29T06:06:06+08:00[Asia/Shanghai]
        - id: before_route
          uri: https://www.ailijie.top
          predicates:
            - After=2020-06-30T06:06:06+08:00[Asia/Shanghai]